package postgres

import (
	"context"
	"os"
	"testing"
	"time"

	"github.com/erikw/gomemo/internal/notes"
	"github.com/jackc/pgx/v5/pgxpool"
)

func TestNoteStoreCRUD(t *testing.T) {
	store, pool := newTestStore(t)
	defer pool.Close()

	ctx := context.Background()
	if err := store.Clear(ctx); err != nil {
		t.Fatalf("Clear() error = %v", err)
	}

	createdAt := time.Now()
	n, err := store.Create(ctx, &notes.Note{
		Title:      "first",
		Content:    "content",
		CreatedAt:  createdAt,
		ModifiedAt: createdAt,
	})
	if err != nil {
		t.Fatalf("Create() error = %v", err)
	}
	if n.ID < 1 {
		t.Fatalf("Create() ID = %d, want >= 1", n.ID)
	}

	got, err := store.FindByID(ctx, n.ID)
	if err != nil {
		t.Fatalf("FindByID() error = %v", err)
	}
	if got.Title != "first" {
		t.Fatalf("FindByID() Title = %q, want %q", got.Title, "first")
	}

	all, err := store.All(ctx)
	if err != nil {
		t.Fatalf("All() error = %v", err)
	}
	if len(all) != 1 {
		t.Fatalf("All() len = %d, want 1", len(all))
	}

	deleted, err := store.DeleteByID(ctx, n.ID)
	if err != nil {
		t.Fatalf("DeleteByID() error = %v", err)
	}
	if !deleted {
		t.Fatal("DeleteByID() expected deleted=true")
	}
}

func TestNoteStoreInsertWithIDUpsert(t *testing.T) {
	store, pool := newTestStore(t)
	defer pool.Close()

	ctx := context.Background()
	if err := store.Clear(ctx); err != nil {
		t.Fatalf("Clear() error = %v", err)
	}

	now := time.Now()
	first, err := store.InsertWithID(ctx, 42, &notes.Note{
		Title:      "v1",
		Content:    "v1",
		CreatedAt:  now,
		ModifiedAt: now,
	})
	if err != nil {
		t.Fatalf("InsertWithID() first error = %v", err)
	}
	if first.ID != 42 {
		t.Fatalf("InsertWithID() first ID = %d, want 42", first.ID)
	}

	second, err := store.InsertWithID(ctx, 42, &notes.Note{
		Title:      "v2",
		Content:    "v2",
		CreatedAt:  now,
		ModifiedAt: now.Add(time.Minute),
	})
	if err != nil {
		t.Fatalf("InsertWithID() second error = %v", err)
	}
	if second.Title != "v2" {
		t.Fatalf("InsertWithID() second title = %q, want %q", second.Title, "v2")
	}
}

func newTestStore(t *testing.T) (*NoteStore, *pgxpool.Pool) {
	t.Helper()

	databaseURL := os.Getenv("TEST_DATABASE_URL")
	if databaseURL == "" {
		t.Skip("TEST_DATABASE_URL is not set")
	}

	pool, err := pgxpool.New(context.Background(), databaseURL)
	if err != nil {
		t.Fatalf("pgxpool.New() error = %v", err)
	}

	if _, err := pool.Exec(context.Background(), `
		CREATE TABLE IF NOT EXISTS notes (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			title TEXT NOT NULL,
			content TEXT NOT NULL DEFAULT '',
			created_at TIMESTAMPTZ NOT NULL,
			modified_at TIMESTAMPTZ NOT NULL
		)
	`); err != nil {
		pool.Close()
		t.Fatalf("create table error = %v", err)
	}

	return NewNoteStore(pool), pool
}
